---
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install packages
        uses: bahmutov/npm-install@v1.4.5

      - name: Prettier
        run: yarn run lint

      - name: Install Gatsby
        run: yarn add global gatsby

      - name: Build Gatsby website
        run: yarn run build

      - name: Deploy website
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: gh-pages
          access-token: ${{ secrets.ACCESS_TOKEN }}        
