---
name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install packages
        uses: jaid/action-npm-install@v1.2.1

      - name: Prettier
        run: yarn run lint

      - name: Install Gatsby
        run: yarn add global gatsby

      - name: Build Gatsby website
        run: yarn run build

