---
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3

      - name: npm install
        uses: jaid/action-npm-install@v1.2.1

      - name: Run Prettier
        run: prettier --check .

      - name: Install Gatsby
        run: npm install -g gatsby --no-save

      - name: Build Gatsby website
        run: gatsby build

